site_name: GIRA3D Reconstruction

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
plugins:
  - mkdocs-jupyter:
      execute: false


repo_name: 'rislab/gira3d-benchmarking'
repo_url: 'https://github.com/rislab/gira3d-benchmarking'

nav:
  - Home: 'index.md'
  - Tutorials:
    - 'Python Binding over OctoMap' : 'tutorials/octomap-py-tut.ipynb'
    - 'Python Binding over NDTMap' : 'tutorials/ndtmap-py-tut.ipynb'
